#!/usr/bin/env bash
#redirection must be a “301 Moved Permanently”
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World" | sudo tee  /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=KfGr49Z7OaA&ab_channel=LaithAcademy permanent;' /etc/nginx/sites-available/default 
sudo service nginx start
