#!/usr/bin/env bash
#redirection must be a “301 Moved Permanently”
./1-install_nginx_web_server
redirection=""
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default 