#!/usr/bin/env bash
# Customize 404 page that contains the string 'Ceci n'est pas une page'

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' |sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me 301;' /etc/nginx/sites-available/default
sudo touch /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx start
