#!/usr/bin/env bash
# Configures a new Ubuntu server and add a custom HTTP header response
# shellcheck disable=SC2154
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.dictionary.com/browse/redirect permanent;' /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
service nginx start

