#!/usr/bin/env bash
# Configures a new Ubuntu server and add a custom HTTP header response
# shellcheck disable=SC2154
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.dictionary.com/browse/redirect permanent;' /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx start

