#!/usr/bin/env bash
# Install and configure load balancer
sudo apt-get -y install haproxy
var=\
"
frontend http_web
        bind *:80
        stats uri /haproxy?stats
        default_backend proxy_backend
backend proxy_backend
        balance roundrobin
        server 4257-web-01 54.144.49.141:80 check
        server 4257-web-02 54.242.182.44:80 check
"
 echo "$var" | sudo tee /etc/haproxy/haproxy.cfg
 echo "ENABLED=1" | sudo tee /etc/default/haproxy
 sudo service haproxy stop
 sudo service haproxy start
